version: '3.6'

services:
  smart-brain-api:
    container_name: backend
    image: node:latest
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-api
    environment:
      POSTGRES_URI: postgres://docker:docker@postgres:5432/docker-seeded
      JWT_SECRET: docker-secret
      REDIS_HOST: redis://redis:6379
    ports:
      - "4400:4400"
    volumes:
      - ./:/usr/src/smart-brain-api

  # Postgres
  postgres:
    build: ./postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker-seeded
    ports:
      - "5434:5432"

  # Redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"